baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Jaywhen"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 6                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "Jaywhen"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
#[[menu.main]]
#  name = "Tags"
#  weight = 30
#  identifier = "tags"
#  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 30
  identifier = "about"
  url = "/about/"
  
[[menu.main]]
  name = "CV"
  weight = 30
  identifier = "CV"
  url = "/cv/"

[params]
  subTitle = "此际回头看，原来并没有事"                                       # site's subTitle  # 网站二级标题
  # footerSlogan = "My spiritual home"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["Jaywhen","Xiang Jiewen","hellocode"]                                  # site's keywords  # 网站关键字
  description = "Jaywhen's blog"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = false                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = "e40phb6mkqAQo62eczyPH73A-gzGzoHsz"
  appKey = "VhiNamqTQY7CqF1inCYgyKol"
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = "https://github.com/jaywhen"
  bilibili = "https://space.bilibili.com/129382476"
  twitter = "https://twitter.com/jaywhen6"
  instagram = "https://www.instagram.com/jaywhenx/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
